// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjlUMnOXMFeUJ3GQ_7QHWCy54pTV9VXro',
    appId: '1:231270698505:web:582fdcd5d4bd39ac96f2d8',
    messagingSenderId: '231270698505',
    projectId: 'visible-b9c23',
    authDomain: 'visible-b9c23.firebaseapp.com',
    storageBucket: 'visible-b9c23.firebasestorage.app',
    measurementId: 'G-QZRDJH5PM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8Rc7gyQsvxZM1bGSImvN8SFEIAox9dg',
    appId: '1:231270698505:android:4ac2b5f49457b75e96f2d8',
    messagingSenderId: '231270698505',
    projectId: 'visible-b9c23',
    storageBucket: 'visible-b9c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1YyZt1zM8nwSrShcgPmo92XoKUDjrphE',
    appId: '1:231270698505:ios:131fd65ad0b1be9396f2d8',
    messagingSenderId: '231270698505',
    projectId: 'visible-b9c23',
    storageBucket: 'visible-b9c23.firebasestorage.app',
    iosBundleId: 'com.example.visible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1YyZt1zM8nwSrShcgPmo92XoKUDjrphE',
    appId: '1:231270698505:ios:131fd65ad0b1be9396f2d8',
    messagingSenderId: '231270698505',
    projectId: 'visible-b9c23',
    storageBucket: 'visible-b9c23.firebasestorage.app',
    iosBundleId: 'com.example.visible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjlUMnOXMFeUJ3GQ_7QHWCy54pTV9VXro',
    appId: '1:231270698505:web:5239545fd300200596f2d8',
    messagingSenderId: '231270698505',
    projectId: 'visible-b9c23',
    authDomain: 'visible-b9c23.firebaseapp.com',
    storageBucket: 'visible-b9c23.firebasestorage.app',
    measurementId: 'G-20CXZTYE0Q',
  );
}
